name: Fontana de la pagina
on: 
  push:
    branches:
      - master
    jobs:
      deploy-page:
        runs-on: ubuntu-latest
        steps:
        - name: Chekout
          uses: actions/checkout@v2.3.1

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with:
          brach: gh-pages
          folder: public
  
